### ISSUE TITLE
iOS 9 warnings for deprecated AddressBook

### ISSUE THREAD

**Issue by JamieWhite** [danthorpe/Operations#111]
What's the best way to silence these?

I'm targeting iOS 9 and using carthage to include this in my project. I got a load of warnings when compiling the frameworks and continue to get warnings from my xcodeproj that imports the framework.

**Comment by danthorpe** [comment]
Hi @JamieWhite - thanks for the feedback. 

Unfortunately, if using Carthage there isn't much that can be done about this right now. With CocoaPods the AddressBook stuff is not included by default. 

However, I'll look into fixing this one way or another as it must be a pain. Stay tuned for a point release...

**Comment by JamieWhite** [comment]
Cool thanks. I think I'll fork for now and rip out the AddressBook stuff.

**Comment by danthorpe** [comment]
Okay, for what it's worth, I should be able to fix this today and released 2.4.1, as I think it's fairly trivial, see my answer from two months ago: http://stackoverflow.com/questions/31540446/how-to-silence-a-warning-in-swift-2-0/32970249#32970249

But if you've got stuff to do, just need to untick them from the targets. When I release v3.0 I'll drop support for iOS 8 and they'll get removed.

**Comment by JamieWhite** [comment]
I was previously using PSOperations but I saw you have better swift support so I thought I'd see how easy it would be to migrate. I've got migration for this in a branch (it was really easy). For the time being I'll just keep using PSOperations if you're planning on sorting this out in 2.4.1

**Comment by danthorpe** [comment]
Okay, sounds good. I will close this issue when a release is available which has removed these warnings - so you'll get notified.

**Comment by danthorpe** [comment]
Hi @JamieWhite, just a quick update on this. It's been fixed, and is in `development` branch. The other issue with the extensions - that's a more tricky issue, see: https://github.com/danthorpe/Operations/pull/114 currently waiting for a PR in Carthage to be merged.

I'm considering releasing the fix for the warnings as 2.4.1 - was wondering if you were able to point your `Cartfile` at the `development` branch of this repo and see how it works for you?

**Comment by JamieWhite** [comment]
Works fantastic now. I built then saw the same warnings... then trashed my deriveddata folder and rebuilt then the warnings went.

I don't even get the extension warning now for some reason. I have a feeling that's an xcode issue though and it'll likely crop up again later.

Thanks for your rapid response on this though.

**Comment by danthorpe** [comment]
Okay, I'm gonna do a point release for this. Thanks for getting back to me and for raising the issues!

**Comment by JamieWhite** [comment]
No problem. Thanks for building this awesome framework from that also awesome NSOperations sample

**Comment by JamieWhite** [comment]
Well it looks like these warnings are showing up for me again. The problem seems to be in the generated Objective C header.

**Comment by danthorpe** [comment]
Hi @JamieWhite - can you check on the `release/2.4.1` branch?

**Comment by JamieWhite** [comment]
Seems to still be occurring.

Cartfile: github "danthorpe/Operations" "release/2.4.1"
Cartfile.resolved: github "danthorpe/Operations" "a5757a66106c4a72f010c67591a5461c8c566436"

**Comment by danthorpe** [comment]
Yeah, I'm looking into it too - I think before, I marked all of the types as deprecated, which removes the warnings - but these don't get auto generated (in Operations-Swift.h) as you say. Hmm, not really sure about this. Maybe just pull the trigger, release v3.0 move to iOS 9.0 deployment target and remove them? It's the Apple way!

**Comment by JamieWhite** [comment]
Is there any way we could conditionally compile the addressbook stuff? So basically don't include it when built for iOS 9

**Comment by danthorpe** [comment]
I don't think it's possible to conditionally compile based on the deployment target. We always build against latest, but you're deployment target is > 8 which is why you're seeing the warnings. But, some people are definitely still supporting iOS 8 - so I can't break things working without a major new version.

This is actually where CocoaPods has some advantages I think, because it will import the source into your own environment.

**Comment by JamieWhite** [comment]
Would it be insane to drop Objective C support?

**Comment by danthorpe** [comment]
@JamieWhite what warnings do you see? I get this...

![warnings](https://cloud.githubusercontent.com/assets/309420/11608503/5aa383ca-9b63-11e5-9f17-b16a84d2db9a.png)

**Comment by danthorpe** [comment]
Well, I've been planning (mostly thinking about how) to do a version which doesn't use `NSOperation` and `NSOperationQueue` - given the foundation open source news, this is really interesting, as they're going to effectively open up the source of `NSOperation` - see: https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSOperation.swift

But, I mean, Swift by default inter-ops with Objective-C - not really sure what you mean by dropping support for Objective-C?

**Comment by danthorpe** [comment]
But anyway, I only get 3 warnings now - which is significantly better than it was? And I can probably fix this by using `Int32` or a typealias instead of `ABRecordID` in those signatures.

**Comment by JamieWhite** [comment]
I get the same warnings as you. The fix you suggested sounds good

By dropping Objective-C I was suggesting not generating the Objective C header - your fix sounds is obviously much better and less drastic.

and yeah it's going to be exciting to see how Apple implements some of these things.

**Comment by danthorpe** [comment]
Okay, I think  I've fixed this now...

Cartfile:
```
github "danthorpe/Operations" "release/2.4.1"
```

carthage command:

```
$ carthage update
*** Fetching Operations
*** Checking out Operations at "44fa832a40f902abd46a171c14f9be75491b8371"
*** xcodebuild output can be found in /var/folders/6j/9k2drdbs1fv9fw5d6wng5yzh0000gn/T/carthage-xcodebuild.0tZNgK.log
*** Building scheme "OS X Operations" in Operations.xcodeproj
*** WARNING: Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed
*** Building scheme "watchOS Operations" in Operations.xcodeproj
*** Building scheme "tvOS Operations" in Operations.xcodeproj
*** Building scheme "iOS Operations" in Operations.xcodeproj
$
```

No warnings:

![no warnings](https://cloud.githubusercontent.com/assets/309420/11608575/f6d8513e-9b64-11e5-854d-cd886f29e910.png)

**Comment by JamieWhite** [comment]
Sorted :+1:

**Comment by danthorpe** [comment]
Note also, that if you do use AddressBook related stuff - with a minimum deployment set to 9.0, then you get deprecation warnings..

![get warnings](https://cloud.githubusercontent.com/assets/309420/11608635/d0e3b3fe-9b66-11e5-8034-3b714e7e910e.png)

**Comment by JamieWhite** [comment]
I think you'd be daft to use AddressBook when you have the new Contacts stuff.

**Comment by danthorpe** [comment]
Yeah, but again, I wrote it when I needed it for iOS 8 minimum deployment stuff. And I've actually just discovered a bug here! 

That is definitely an issue with `@testable` - it's very easy to accidentally leave a property as internal instead of public.

**Comment by danthorpe** [comment]
Okay, so I think we're good with 2.4.1 yeah?

**Comment by JamieWhite** [comment]
Yeah. Good work.

**Comment by danthorpe** [comment]
Yeah, just sorting out the docs now - so that the podspec will lint.

**Comment by danthorpe** [comment]
Thanks for all your help with this @JamieWhite - if you find any more issue, just create an issue and I'll sort them out. I'm not actively using this framework much at the moment - but want to keep on top of it. Similarly, if there is anything feature wise which is missing - let me know. :)

**Comment by danthorpe** [comment]
Okay, closing this now, 2.4.1 is released which has a fix for the issue.
