### ISSUE TITLE
Operations from mutually exclusive conditions start too early

### ISSUE THREAD

**Issue by kevinbrewster** [danthorpe/Operations#129]
Disclaimer: this may be considered a bug fix, feature request, or my mis-understandings of how the Operations framework should work.

Anyway, consider the following code:

```swift
class ViewController: UIViewController {
    let queue = OperationQueue()
    
    override func viewDidLoad() {
        super.viewDidLoad()
     
        let op1 = BlockOperation {
            NSLog("Doing something with download")
        }
        op1.addCondition(CheckDownloadedCondition())
        
        let op2 = BlockOperation {
            NSLog("Doing something else with download")
        }
        op2.addCondition(CheckDownloadedCondition())
        
        queue.addOperations([op1, op2], waitUntilFinished: false)
    }
}

class DownloadOperation : Operation {
    override func execute() {
	    // in reality, we would first we check if already downloaded
        NSLog("Starting long download")
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(2.0 * Double(NSEC_PER_SEC))), dispatch_get_main_queue()) { () -> Void in
            NSLog("Finished long download")
            self.finish()
        }
    }
}
public struct CheckDownloadedCondition: OperationCondition {
    public var name: String { return "CheckDownloadedCondition" }
    public var isMutuallyExclusive: Bool { return true }
    
    public func dependencyForOperation(operation: Operation) -> NSOperation? {
        return DownloadOperation()
    }
    public func evaluateForOperation(operation: Operation, completion: OperationConditionResult -> Void) {
        completion(.Satisfied)        
    }
}
```

My intent is that both `op1` and `op2` need the same thing before they can start (e.g. a large file downloaded from the internet). So if I create a mutuallyExclusive `OperationCondition` that returns a `dependencyForOperation`, I expect the condition decencies to be mutually exclusive. Meaning, the second `DownloadOperation` wouldn't start until the first `DownloadOperation` completes. That way I don't have to do two downloads.

But as it stands now, both `DownloadOperation's` will execute concurrently, which is not desirable.

The relevant code in `OperationQueue.addOperation` looks like this:

```swift
let dependencies = operation.conditions.flatMap {
	$0.dependencyForOperation(operation)
}

for dependency in dependencies {
	operation.addDependency(dependency)
	addOperation(dependency)
}

let concurrencyCategories: [String] = operation.conditions.flatMap { condition in
	if !condition.isMutuallyExclusive { return .None }
	return "\(condition.dynamicType)"
}

if !concurrencyCategories.isEmpty {
	manager.addOperation(operation, categories: concurrencyCategories)

	operation.addObserver(BlockObserver(finishHandler: { (operation, _) in
		manager.removeOperation(operation, categories: concurrencyCategories)
	}))
}
```
and in my example, this code simply makes `op2` dependent on `op1`, which doesn't prevent the  `DownloadOperation's` from executing concurrently.

I propose we replace that section of code with this:

```swift
let manager = ExclusivityManager.sharedInstance
for condition in operation.conditions {
	let dependency = condition.dependencyForOperation(operation)
	
	if condition.isMutuallyExclusive {
		let mutuallyExclusiveOp = dependency ?? operation
		
		manager.addOperation(mutuallyExclusiveOp, category: "\(condition.dynamicType)")
		
		operation.addObserver(BlockObserver(finishHandler: { (operation, _) in
			manager.removeOperation(mutuallyExclusiveOp, category: "\(condition.dynamicType)")
		}))
	}
	if dependency != nil {
		operation.addDependency(dependency!)
		addOperation(dependency!)
	}
}
```

and then ExclusivityManager.swift could be simplified to:

```swift
internal class ExclusivityManager {

    static let sharedInstance = ExclusivityManager()

    private let queue = Queue.Initiated.serial("me.danthorpe.Operations.Exclusivity")
    private var operations: [String: [NSOperation]] = [:]

     func addOperation(operation: NSOperation, category: String) {
        var operationsWithThisCategory = operations[category] ?? []

        if let last = operationsWithThisCategory.last {
            operation.addDependency(last)
        }
        operationsWithThisCategory.append(operation)
		operations[category] = operationsWithThisCategory
    }
    func removeOperation(operation: NSOperation, category: String) {
        let matchingOperations = operations[category]

        if  var operationsWithThisCategory = matchingOperations,
            let index = operationsWithThisCategory.indexOf(operation) {
                operationsWithThisCategory.removeAtIndex(index)
                operations[category] = operationsWithThisCategory
        }
    }
}
```
which would have the desired effect of making the second `DownloadOperation` wait until the first `DownloadOperation` completes.

Here is a diagram of the current and proposed dependency relationships 
![code_explanation](https://cloud.githubusercontent.com/assets/3279697/11773783/b0daadb4-a1fc-11e5-8ac1-638fc8e3b15a.png)

**Comment by danthorpe** [comment]
Hi @kevinbrewster - interesting ideas, and I appreciate that the current behavior might be a bit unexpected. My gut says that it might be a little harder to reason/debug/understand what is going on if the dependencies between operations are transitioned to dependencies between their own dependencies depending on mutual exclusivity.

Personally, I would prefer to use `OperationGroup` and be more explicit in with the dependencies placing mutual exclusivity locks at the highest level.

But regardless I'll look through this and see how it would affect other typical usage.

**Comment by kevinbrewster** [comment]
@danthorpe - would you mind sending me an email? I have a few ideas i want to bounce off you.

**Comment by danthorpe** [comment]
Hi @kevinbrewster just reading through this again.

While I appreciate that this is a contrived example to illustrate your point, the main thing which jumped out at me, why use conditions for this? Maybe I'm missing something, (are the two downloads different resources?), but can you do:

```swift
let download = DownloadOperation()
let one = OperationOne()
one.addDependency(download)
let two = OperationTwo()
two.addDependency(download)
queue.addOperations([download, one, two], waitUntilFinished: false)
```

So... to extract your proposition from the example, you're suggesting that dependencies needed to fulfill mutually exclusive conditions should also be mutually exclusive? I'm just wondering if that logic is correct all the time. It probably is.

However, your proposal would break quite a few things by changing the dependency relationships. You can see it in your diagram - OP1 depends on OP2 && Download1, but your proposal will alter this to be OP1 only depends on Download1. This fundamentally ignores any of the processing of OP2 - which may be a GroupOperation, or produce another operation, or have its own data processing which must occur before OP1 is ready.

So, while I can see that yes, dependencies of mutually exclusive conditions which are attached to operations which are themselves in a dependency graph, should assume the equivalent dependency graph - I think attempting to infer this automatically introduces quite a bit of "magic" into things. 

It is probably clearer (easier to reason about, debug, read) by adding a `MutuallyExclusive` condition to the dependent operation. In your example, I would just make `DownloadOperation` mutually exclusive (with a private constraint, and not make `CheckDownloadCondition` mutually exclusive. 

You can see an example of this pattern by looking at [`UserConfirmationCondition`](https://github.com/danthorpe/Operations/blob/development/Sources/Features/iOS/UserConfirmationCondition.swift). In this case, the condition is not mutually exclusive, but it has a dependency ([`AlertOperation`](https://github.com/danthorpe/Operations/blob/development/Sources/Core/iOS/AlertOperation.swift#L74)) which defines its own exclusivity.

**Comment by kevinbrewster** [comment]
Yes, my example is contrived and just used to give a simple example. In reality it wouldn't make sense to have a "global" operation for which future operations can depend on.

>However, your proposal would break quite a few things by changing the dependency relationships. You can see it in your diagram - OP1 depends on OP2 && Download1, but your proposal will alter this to be OP1 only depends on Download1. This fundamentally ignores any of the processing of OP2 - which may be a GroupOperation, or produce another operation, or have its own data processing which must occur before OP1 is ready.

No, my diagram shows that currently OP2 depends on OP1. To me, this is not desired and is an incorrect "interpretation" of my written code. My code says that both operations depend on a mutually exclusive condition. That should mean that  condition operations should wait for the previous condition operations to finish. 

>  This fundamentally ignores any of the processing of OP2 - which may be a GroupOperation, or produce another operation, or have its own data processing which must occur before OP1 is ready.

Well again, in my code I never asked for OP2 to be dependent on OP1 because I don't need it to be. If I did, I would add OP1 as a dependency to OP2.  Or I would explicitly make those two operations mutually exclusive.

>  I think attempting to infer this automatically introduces quite a bit of "magic" into things.

For end-users, it's just as "magical" to have OP2 depend on OP1 (and it makes less sense in this situation) than it is to have the second condition op dependent on the first condition op. It's much harder to reason about the current code because it's entirely non-intuitive. 

> It is probably clearer (easier to reason about, debug, read) by adding a MutuallyExclusive condition to the dependent operation. In 

I agree that is a viable workaround but it doesn't solve the core issue: The current code doesn't follow the intent of the programmer which leads to problems/confusion.

**Comment by danthorpe** [comment]
Hi @kevinbrewster - sorry didn't go back to your code example to compare with the diagram. I'll write some tests to further investigate this. Depending on how you want to interpret mutual exclusivity there is a bug with the current implementation. So these the things to address:

1. Clarify the expected behavior of attaching mutual exclusive conditions
2. Fix any bugs which cause deviation from this.

**Comment by danthorpe** [comment]
FYI @kevinbrewster - this has now been fixed (I think), and is merged in development.

**Comment by danthorpe** [comment]
Doing some housekeeping - closing this issue now.
