### ISSUE TITLE
Errors in nested group operations don't aggregate up

### ISSUE THREAD

**Issue by bastianschilbe** [danthorpe/Operations#197]
The error produced by an operation inside a group operation which is executed in another group operation isn't aggregated to the outer group operation. There is also a comment in code which says that it is explicitly avoided to add the errors to prevent duplicating all errors. But shouldn't this test run:

        let failingOperation = BlockOperation { (continueWithError) -> Void in
            continueWithError(error: NSError(domain: "", code: 1, userInfo: nil))
        }
        let innerGroup = GroupOperation(operations: [failingOperation])
        let outerGroup = GroupOperation(operations: [innerGroup])
        let queue = OperationQueue()
        
        let expectation = expectationWithDescription("Check Errors")
        
        outerGroup.addObserver(FinishedObserver(didFinish: { (op, errors) -> Void in
            XCTAssertTrue(!errors.isEmpty)
            expectation.fulfill()
        }))
        
        queue.addOperation(outerGroup)
        
        waitForExpectationsWithTimeout(1, handler: nil)

**Comment by danthorpe** [comment]
@bastianschilbe - yeah, I think you might have discovered a regression here! I'll have a look into it. When I added that comment: the `GroupOperation` was automatically getting the errors from any nested `GroupOperation`, but maybe this has stopped happening.

But yeah - I will look into this - good shout!

**Comment by danthorpe** [comment]
Hi @bastianschilbe - thanks for this bug report. You were totally correct! 👍

Anyway, I'm pretty sure that I've fixed it now, merged into `development`. If you have a chance to work on the dev that would be great. Let me know how you get on, and hopefully this can be closed 😀.

FYI - There are some breaking changes on `development` related to operation observers. Hopefully not too serious for you though.

**Comment by danthorpe** [comment]
I'm doing some clean up - pretty sure that this is fixed. @bastianschilbe please re-open if not :)
