### ISSUE TITLE
Subclassing RepeatedOperation is very painful

### ISSUE THREAD

**Issue by jshier** [danthorpe/Operations#199]
Due Swift's subclass initializer requirements (a subclass' designated initializer must call the superclass' designated initializer, not a convenience initializer, and a subclass must have a designated initializer) creating a subclass of `RepeatedOperation` is quite painful, as the required convenience generators and such are not public. In order to create my initializer, as such:
```swift
init(operationGenerator: () -> T?) {
    let generator = RepeatingGenerator(anyGenerator(operationGenerator))
    let strategy = WaitStrategy.Fixed(5)
    let delay = MapGenerator(strategy.generator()) { Delay.By($0) }
    let tuple = TupleGenerator(primary: generator, secondary: delay)
    
    super.init(maxCount: nil, generator: anyGenerator(tuple))
}
```
I had to make public the types, initializer, and `next()` of `RepeatingGenerator`, `WaitStrategy`'s `generator()`, `MapGenerator`, and `TupleGenerator`.

Obviously this isn't a viable solution. Could the library be updated to make the relevant types and properties public? Or is there some other way I'm supposed to be subclassing `RepeatedOperation`?

**Comment by danthorpe** [comment]
Hi @jshier - this is great feedback - I've not tried subclassing this outside of the module. It can definitely be improved. :)

I think if I make the convenience initializers in `RepeatedOperation` all designated initializers (effectively), which will make the library code a little bit less neat, then it'll be much easier for consumers to subclass it. I was also thinking of making the initializer available in the extension (for `T: Repeatable`) available by default.

Also, I am a little bit torn between making some of these internal types public. E.g. `ReachabilityManager`, `MapGenerator`, `FiniteGenerator` etc. On the plus side - they're very helpful, on the con side, it means supporting them (which is restrictive when it comes to refactoring/rewriting). What do you think?

**Comment by jshier** [comment]
I think if the initializers allow the flexibility the convenience initializers expose, then exposing the underlying types would be unnecessary. However, I can see how opening up the initializers like that would lead to some rather messy and duplicate code. I would lean towards the initializer path since once those are open the need for external developers to use the other types is essentially eliminated, unless they're creating other types of generators.

**Comment by danthorpe** [comment]
Yep - I agree. Take the hit on `RepeatedOperation` becoming a little messy by "opening up" (i.e. remove `convenience` and *just making it work*), instead of making public all the helper generators and other things.

Can always make public later and refactor the internals of `RepeatedOperation` later.

**Comment by danthorpe** [comment]
Hi @jshier - I've made quite a few changes to `RepeatedOperation` and `RetryOperation` to hopefully make subclassing them a lot easier and less painful. 

If your `Operation` subclass conforms to `Repeatable` then you will still need to use `RepeatableGenerator` which is now public. So, from your example:

```swift
class MyRepeatedOperation<T where T: NSOperation, T: Repeatable>: RepeatedOperation<T> {
    init(body: () -> T?) {
        super.init(strategy: .Fixed(5), generator: RepeatableGenerator(anyGenerator(body)))
    }
} 
```

Let me know how it goes. Hopefully this issue is resolved.

**Comment by danthorpe** [comment]
These changes are now on the `development` branch.

**Comment by danthorpe** [comment]
Hi @jshier I'm doing some clean up and closing this issue, please re-open if you still have any issues subclassing `RepeatedOperation` :)
