### ISSUE TITLE
Sources/Features/Shared/CloudCapability.swift should be included in tvOS PodSpec

### ISSUE THREAD

**Issue by tbaggett** [danthorpe/Operations#205]
tvOS doesn't currently support retrieving a user's contacts information via discoverAllContactUserInfosWithCompletionHandler. However, it does support checking the user's iCloud account status with [accountStatusWithCompletionHandler](https://developer.apple.com/library/prerelease/tvos/documentation/CloudKit/Reference/CKContainer_class/index.html#//apple_ref/occ/instm/CKContainer/accountStatusWithCompletionHandler:). 

The CloudCapability.swift file is currently excluded from the tvOS target in the PodSpec file. It should be included for tvOS as well, possibly with some "#if os(tvOS) checks" to exclude the permissions portion of the code.

**Comment by danthorpe** [comment]
Arr - good spot, thanks @tbaggett. Will look into this today as a 2.6.0 bug, and release it as 2.6.1.

**Comment by danthorpe** [comment]
@tbaggett this is now fixed on this branch: `hotfix/OPR-205_tvOS_cloud_capability`. If you can try it, that would be great. Change your Podfile so that you have:

```ruby
pod 'Operations', :git => 'https://github.com/danthorpe/Operations', :branch => 'hotfix/OPR-205_tvOS_cloud_capability'
```

I did create a sample app to check that it all compiles, but I've not got entitlements set up, so can't *really* test it right now. Hopefully should be easier for you. 

Let me know how it goes, and I'll create 2.6.1 release.

**Comment by tbaggett** [comment]
Awesome, thanks for the quick response! I will test this today and get back to you with the results.

**Comment by tbaggett** [comment]
Its working great, no problem. I set breakpoints in the CloudCapability verifyAccountStatus method and confirmed that it was being called and that the "Available" CKAccountStatus was returned when I passed in my custom container name.

**Comment by danthorpe** [comment]
Great. It's about midnight here in London. Will merge and do v2.6.1 tomorrow morning (in about 8 hours). 

Thanks for the feedback!

**Comment by danthorpe** [comment]
Okay, this has been merged as a hot fix. Will be in `2.6.1`, `master` and `development` later today.
