### ISSUE TITLE
Example for RetryOperation

### ISSUE THREAD

**Issue by vamsiac** [danthorpe/Operations#243]
Struggling to find a way to generate RetryOperation?

```
let uploadOp = PostMachineUpdateOperation()

uploadOp.addObserver(DidFinishObserver { operation,errors in
   if let error = errors.first! as ErrorType? {
                let errOperation = AppAlertOperation(error: error, from: self)
                self.operationQueue.addOperation(errOperation)

                errOperation.alert.addAction(UIAlertAction(title: "Retry", style: UIAlertActionStyle.Default, handler: { action in

      //HOW TO CREATE A RETRY OPERATION?
      let operation = RetryOperation(anyGenerator(PostMachineUpdateOperation()), retry: retry)
                    self.operationQueue.addOperation(operation)

             })

    }
})
```

**Comment by danthorpe** [comment]
Hi @vamsiac - a great place to start looking for examples of `RetryOperation` is in the project itself. Both the [unit tests](https://github.com/danthorpe/Operations/blob/development/Tests/Core/RetryOperationTests.swift), and also other classes, such as [`CloudKitOperation`](https://github.com/danthorpe/Operations/blob/development/Sources/Features/Shared/CloudKitOperation.swift#L253).

I hope that the [header docs](https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/RetryOperation.swift#L88) in the class will give a good indication of what to do.

But in essence the class works by using a `GeneratorType` of your `Operation` instances. If the operation finishes with error then the `RetryOperation` will get the next instance and try again.

There is also a "retry handler" which is a block the `RetryOperation` can also be initialized with, and this can be used to modify/refine the next operation using error information from the previous instance.

Additionally, there is the concept of a delay between attempts. The generator discussed above actually is for a `Payload` which is a tuple of `(Delay?, T)` where `T` is the operation type. Given this, there are other constructors which can create this `Delay` automatically, such as for exponential back off , random or fixed delays.

And lastly, there is a `maxCount` argument which can limit the number of attempts made before eventually failing the `RetryOperation` itself.

The other way to end the `RetryOperation` is to return `nil` from the generator.

Hope that makes sense - fully aware that I've not got full programming guide or docs on this yet, but if you read the [source header docs](http://docs.danthorpe.me/operations/2.8.0/Classes/RetryOperation.html) it hopefully makes it clearer?

**Comment by vamsiac** [comment]
Cheers Dan, definitely unit tests helped me in lot of other cases but not this one.

```
    typealias Test = PostMachineUpdateOperation
    typealias Retry = RetryOperation<Test>
    typealias Handler = Retry.Handler

```

        let uploadOp = PostMachineUpdateOperation()

cannot create RetryOperation for the above operation 

`let operation = RetryOperation(anyGenerator(XXXXXXXX) , retry: retry)`
XXXXXXX what should i enter here to create a new instance of PostMachineUpdateOperation()


I am sorry new to functional stuff, trying to get my head around it.

**Comment by danthorpe** [comment]
Yeah, that's no worries - so you'd do something like this:

```swift
let operation = RetryOperation(anyGenerator { PostMachineUpdateOperation() })
```

See docs [here](http://swiftdoc.org/v2.1/func/anyGenerator/#func-anygenerator-element_-element) on `anyGenerator`.

**Comment by danthorpe** [comment]
I think in the unit tests, because I need to create operations, which fail N times and then succeed, I have that logic wrapped up into a `produce` function, which is just returning a closure. i.e.

```swift
func produce() -> () -> PostMachineUpdateOperation? {
    // Return a closure
    return {
        // Return an instance of PostMachineUpdateOperation or nil
    }
}
```

Given something like that you can then also do:

```swift
let operation = RetryOperation(anyGenerator(produce()), retry: retry)
```

**Comment by vamsiac** [comment]
haha, its one of those things I was struggling from this morning and you solved it with two lines.

This helped.
`let operation = RetryOperation(anyGenerator { PostMachineUpdateOperation() }, retry: retry)
`See **docs** here on **anyGenerator**.

**Comment by danthorpe** [comment]
@vamsiac - great. I'm gonna close this for now. Please re-open if you have any more questions on `RetryOperation`. 😀
