### ISSUE TITLE
Bug: MutuallyExclusive operations/condition may prevent execution

### ISSUE THREAD

**Issue by danthorpe** [danthorpe/Operations#246]

**Comment by gvarela** [comment]
I've experienced this when trying to use with CLLocationManager

**Comment by danthorpe** [comment]
Yep - it is an easy fix thanks to @difujia  - I'm just working on getting it merged correctly. There will be a 2.8.1 which has this fix for Swift 2.1.1 and the same fix in 2.9.0 which will be for Swift 2.2.

Hopefully will get it all sorted by this time tomorrow - unfortunately I've run out of time tonight.

**Comment by danthorpe** [comment]
This has been fixed and merged into `swift/2.1` branch. Release pending (later today).
