### ISSUE TITLE
Config option for `waitUntilAllOperationsAreFinished`

### ISSUE THREAD

**Issue by DavidNix** [danthorpe/Operations#258]
A fatal error is raised within `Operation.swift`.

```swift
final override func waitUntilFinished() {
    fatalError("Waiting on operations is an anti-pattern. Remove this ONLY if you're absolutely sure there is No Other Way™. Post a question in https://github.com/danthorpe/Operations if you are unsure.")
}
```

I agree it's an anti-pattern in *production* code.  For unit tests, however, it's useful to force an operation queue to wait.  There are plenty of methods to wait on async code in tests, but I prefer to keep tests as synchronous as possible.  Async test helpers often rely on arbitrary timeouts (slowing the test suite) and often require more boilerplate code to setup.

Perhaps a config option to enable/disable this fatal error?

**Comment by danthorpe** [comment]
Hi @DavidNix - sorry for the delay on getting back to you on this. Been a bit busy at work 😬.

Open to suggestions on how you would do this, but my position at the moment, is that I'm inclined to leave it as it is. Mostly this is because I currently work on a team where they run all their asynchronous code synchronously in the test suite - and there is certainly an element of are we really doing effective or real tests? Also, I'd argue that writing asynchronous tests is not an issue - this codebase has 668 tests, which runs in 23 seconds, and the vast majority of them are asynchronous.

**Comment by DavidNix** [comment]
Hey there,

Now I'm the cause for the delay!

Your test suite contains over 40 instances of `waitForExpectationsWithTimeout`.
There's nothing wrong using that feature of XCTest. But, synchronous tests
eliminate the need for such boilerplate.

To be clear, I am a fan of synchronous tests for unit tests only.
Obviously, integration/feature tests should be async where appropriate.

My suggestion would be a static var on `Operation`. Ex:
`Operation.allowWaitUntilFinished = true`

I really like the features in this library. Unfortunately, I decided not to
use it in my project. And this wait-until-finished decision was a
significant factor.

However, I am very impressed by the features and depth of your library.
This definitely took a lot of work and has taught be a lot about composable
NSOperations.

On Fri, Apr 1, 2016 at 3:59 AM Daniel Thorpe <notifications@github.com>
wrote:

> Hi @DavidNix <https://github.com/DavidNix> - sorry for the delay on
> getting back to you on this. Been a bit busy at work 😬.
>
> Open to suggestions on how you would do this, but my position at the
> moment, is that I'm inclined to leave it as it is. Mostly this is because I
> currently work on a team where they run all their asynchronous code
> synchronously in the test suite - and there is certainly an element of are
> we really doing effective or real tests? Also, I'd argue that writing
> asynchronous tests is not an issue - this codebase has 668 tests, which
> runs in 23 seconds, and the vast majority of them are asynchronous.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/danthorpe/Operations/issues/258#issuecomment-204335891>
>
-- 
Thanks,

David

**Comment by danthorpe** [comment]
Okay - thanks for getting back me! Will close this now.

**Comment by iheart2code** [comment]
I would appreciate if there were some resolution on this, as this is impacting me as well.

**Comment by danthorpe** [comment]
Hi @iheart2code - what issue are you having?

**Comment by iheart2code** [comment]
I am writing some integration tests and need to wait for a composition of operations to complete (or fail). I've kind of worked around this for now using key-value observation with ReactiveCocoa.

**Comment by danthorpe** [comment]
Err - well, have you tried adding a `DidFinishObserver` to your operation?

If you have many operations which you need to "wait" for. Another option is to create an empty `Operation` which you make dependent on your set of operations, and then attach observers to that.

**Comment by iheart2code** [comment]
I didn't know about `DidFinishObserver`. I will give that a shot. Thanks!
