### ISSUE TITLE
NetworkOperation / NSURLTaskOperation crashes if task.state is set to .Finished more than once

### ISSUE THREAD

**Issue by mooshee** [danthorpe/Operations#262]
Some libraries (namely: AFNetworking) set the state for the NSURLSessionTask to Finished more than once.  NSURLTaskOperation attempts to unregister the KVO observer each time--crashing on the 2nd attempt.

I ended up using technique similar to the link below with a boolean flag and an NSLock.
https://github.com/pluralsight/PSOperations/blob/master/PSOperations/URLSessionTaskOperation.swift

I'd submit a PR, but I'm wondering if there's something I'm missing?

Side note: NetworkOperation.swift needs to be renamed to NSURLTaskOperation.swift

**Comment by danthorpe** [comment]
Hi @mooshee - thanks for the bug report! I don't use AFNetworking/Alamofire so, didn't know about this.

If you submit a pull request for the bug fix, can you branch from `swift/2.1` and send the PR back to that branch? (And only use Swift 2.1 code). Also please do not change the name. This can then be released in version 2.8.3.

I can then pull the changes into `development` and will consider changing the name in a separate issue for the next release, `2.10.0`.

**Comment by danthorpe** [comment]
This has been fixed, it will be released with v2.10, which can be tested using the branch at #298.

**Comment by mooshee** [comment]
I apologize for not being to get this fix in.  I’ve been in a development frenzy.  This is the first time I’ve used this framework (for two brand new apps) and it’s been fantastic.  Thank you @danthorpe!
