### ISSUE TITLE
Vacuum operation queue

### ISSUE THREAD

**Issue by pomozoff** [danthorpe/Operations#274]
While app is running there are many finished operation with dependencies in the queue still alive and utilize a little bit of memory.
I do not need the most part of them anymore.
How to release unneeded operations to clean up a little memory?

**Comment by danthorpe** [comment]
Hi @pomozoff - thanks for bringing this to my attentions - I wasn't aware that this might be happening.

Is it possible for you to share some minimal example of how this might happen? As you describe it - it sounds more like a bug, which should be fixed. So, what would be useful to know:

1. What is the operation dependency graph when you add them to the queue.
2. What are the operations which are left alive?
3. What are the operation which are still executing / deadlocking / blocking on themselves?

**Comment by danthorpe** [comment]
Hi @pomozoff - I think this issue will not be fixed in `development`. There was a bug (still is in `NSOperation`) which would prevent operations from executing sometimes. This has now been avoided. Please re-open if you can still reproduce this issue - and please share a repeatable example. 😀

**Comment by pomozoff** [comment]
Hi @danthorpe. Thanks for suggesting. I can't describe my issue - the environment is complicated. I'll open it again when will be able to make an example.
