### ISSUE TITLE
Improved BlockCondition

### ISSUE THREAD

**Issue by ryanjm** [danthorpe/Operations#276]
Regarding number 3 from #264 which was about the `BlockCondition` not being able to handle custom error messages.

I created my own block condition which takes a throwing block. This is super rudimentary right now but it does let the block throw its own error to pass along.

Right now, the return type is ignored and I'm not sure how that should be handled yet. If the condition is to fail, it seems like there should be a reason (and therefore an error). It might be better to make the block not return anything?

I've only had a single use case for it yet, so I think I need more examples of how these blocks are being used before figuring out the edge cases.

All that to say, I thought I'd post it here to get a discussion started about it, with the hopes of getting it incorporated into the project.

```swift
class BlockConditionThrowingError: OperationCondition {
    typealias ConditionBlockThrowingErrorType = () throws -> Bool

    let condition: ConditionBlockThrowingErrorType

    init(block: ConditionBlockThrowingErrorType) {
        condition = block
    }

    let name = "Block Condition Throwing Error"
    let isMutuallyExclusive = false

    func dependencyForOperation(operation: Operation) -> NSOperation? {
        return .None
    }

    func evaluateForOperation(operation: Operation, completion: OperationConditionResult -> Void) {
        var success: OperationConditionResult
        do {
            try condition()
            success = .Satisfied

        } catch {
            success = .Failed(error)
        }
        completion(success)
    }
}
```

Is this the right direction and/or how do you think the return of the condition should be used?

**Comment by danthorpe** [comment]
Hi - yeah, I think this is a good way to go. Certainly makes sense to start introducing Swift 2.0 style APIs such as throwing errors. So, pretty sure that we can incorporate this style. Will get back with more info about how I think we should proceed with this, as I'd like to make the same change in `BlockOperation`.
