### ISSUE TITLE
Execute one at a time Operation Condition

### ISSUE THREAD

**Issue by felix-dumit** [danthorpe/Operations#277]
I'm looking for a way to ensure all operations of a certain kind happen one at a time, these operations can be created at different points in the app so I don't think I can have a set `GroupOperation` with `queue.maxConcurrentOperationCount = 1` I can keep adding operations too.

Basically I'm looking for something similar to the `MutuallyExclusive` condition, but that instead of erroring the second operation it will add the previous operation of that kind as dependencies.

Is it possible to do something like that?

This is an initial attempt I did (doesn't compile - can't quite figure out how to store the last operation for a given `T`:

```swift
public struct OneAtATimeCondition<T:Operation>: OperationCondition {

    public var name: String { return  "OneAtATime<\(T.self)>" }
    
    static var lastOp:T? = nil // Static stored properties not yet supported in generic types
    
    public var isMutuallyExclusive = true
    
    public func dependencyForOperation(operation: Operation) -> NSOperation? {
        return self.dynamicType.lastOp
    }
    public func evaluateForOperation(operation: Operation, completion: OperationConditionResult -> Void) {
        self.dynamicType.lastOp = operation as? T
        completion(.Satisfied)
    }
}
```

**Comment by danthorpe** [comment]
Hi @felix-dumit - I think probably the best thing to do here is create your own `OperationQueue` subclass?

**Comment by felix-dumit** [comment]
@danthorpe I'm not sure if it will work in my scenario because this operation is usually executed as part of a `GroupOperation`, and they won't all be under the same Group.

Currently my workaround was to wrap the `execute` method in a `dispatch_barrier_sync` call on a created `dispatch_queue`

**Comment by danthorpe** [comment]
Okay - that's a fairly pragmatic approach. 

I'm gonna close this issue, sounds like you've got it sorted, and it's not something that the framework will support directly.

**Comment by felix-dumit** [comment]
Yeah ok, I was just wondering it there was another way to do it that would be more reusable for other operations
