### ISSUE TITLE
What is the best practice for creating / passing around an OperationQueue?

### ISSUE THREAD

**Issue by cc-lam** [danthorpe/Operations#283]
Hello,
Sorry in advance it this is not the most appropriate place to be asking very general questions like the following.

Instead of creating a new OperationQueue instance for every ViewController, I was wondering if I could just create one (or more) queue(s) in the app delegate and pass them around through dependency injection ?  I cannot think of any obvious downside, but really wanted to check since I'm just starting to get familiar with this library.

Thanks

**Comment by danthorpe** [comment]
Hey @cc-lam! This is a great question, and absolutely an appropriate place to ask questions 👍🙂 

Well... `UIViewController` dependency injection - could probably talk about this at length, and still not really have a definitive answer. It's all about trade offs and what you want to optimise for.

With regard to `OperationQueue`, it's really not much different from `NSOperationQueue` and it's nice that it can be created without any arguments. Also, by default, it will just schedule operations on an appropriate (in terms of quality of service) global queue. Given that, *I think* this is actually quite a nice and pragmatic approach:

```swift
class MyViewController: UIViewController {
    lazy var queue = OperationQueue()
}
```

There are some benefits to this:
1. It's simple
2. It's easy to read and obvious
3. It's *not* inefficient
4. It elegantly avoids any issues with having an `OperationQueue!` property type.
5. It doesn't restrict you from building dependency injection in the future.

However, if you want to customise the queue (perhaps to give it a specific underlying `dispatch_queue_t`) or you just need to include it as part of other dependencies which must be injected, then, the DI route makes sense. Either use a framework like Typhoon, or roll your own system

```swift

protocol Injectable {
    associated type Container
    func inject(_: Container)
}

protocol OperationQueueProvider {
    var queue: OperationQueue { get }
}

protocol FooProvider {
    var foo: Foo { get }
}

class MyViewController: UIViewController {
    var queue: OperationQueue!
    var foo: Foo!
}

extension MyViewController: Injectable {

    func inject(container: protocol<OperationQueueProvider, FooProvider>) {
        queue = container.queue
        foo = container.foo
    }
}
```

And something like this (but, figure out your own system) is okay... But you can see that doing it properly suddenly introduces a lot more bits and bobs. You now need to test that the `inject` method is called at the correct time, and you'll probably need to create a custom `UIStoryboardSegue` if you want to use storyboards. So - to compare:

1. Not simple
2. Not easily readable nor obvious
3. Maybe it's more efficient
4. Has lots of explicitly unwrapped optionals
5. Introduces a patterns through an entire application - this could be good, but also bad, as its now much harder to refactor. While your view controllers might be decoupled, they are still bound by the pattern which enables the decoupling.

But... to answer your question - if you use DI, where does the queue come from? It's a good question, I actually don't think there is anything wrong just putting:

```swift
let queue = OperationQueue()
```

at the top of your AppDelegate.swift file. Not actually in the `AppDelegate` class (as you definitely do not want to be passing that around) - but just somewhere sensible in the scope of your application's module.

I will add - that there is one very clear advantage of using a DI system. This is that in your tests, it's much easier to swap out those dependencies for *testable* equivalents.

Hope that gives you something to think about...

**Comment by cc-lam** [comment]
Thanks for the clarifications.

Cheers!

**Comment by jshier** [comment]
Personally, I prefer the global singleton to the complexity of passing an operation queue between view controllers or the bloat of operation queue properties in controllers. That way, all of my operation logic is contained in a single `OperationQueue` subclass which provides a convenient API for vending operations to whatever needs them. I've shown this pattern before, but I'll produce a version here:
```swift
class OperationManager: OperationQueue {
    private let sharedManager = OperationManager()

    static func someOperation(parameter: String, completionHandler: () -> Void) -> SomeOperation {
        let operation = SomeOperation(parameter: parameter, completionHandler: completionHandler)
        sharedManager.addOperation(operation)

        return operation
    }
}
```
Any view controller that needs something can then just call `OperationManager.someOperation("parameter") { print("operation done") }` and get the operation back. This consolidates all operation creation login into a single class (or set of classes for related groups of operations). It's not really that much different than having a property in the view controllers themselves, but view controllers are big enough as it is, so removing that one property is a win to me.

**Comment by ryanjm** [comment]
I do pretty much the same thing as @jshier. Then benefit I find in having a singleton is that even if the user leaves the view, my operations will still be completed (90% of them right now are downloading / importing data) so the data will be there when the user comes back.
