### ISSUE TITLE
Why is guarding on `cancelled` in `execute` considered best practice?

### ISSUE THREAD

**Issue by nickmshelley** [danthorpe/Operations#287]
It seems like this is already taken into account here: https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/Operation.swift#L535.

**Comment by danthorpe** [comment]
Hi @nickmshelley - it's a really good question, but I don't really have a clear and obvious answer for you. 

I guess you can consider this is just me re-enforcing Apple's guidelines on this - which is to always check (and periodically check) the cancelled state of the operation while doing work. Yes, `Operation` will not call `execute` if the operation is cancelled when `main()` is called, but, could the operation be cancelled at some point between `main` and `execute` - theoretically possible. So, I think it's wise to be a little defensive here to avoid any subtle race condition behaviours.

But... in the grand scheme of things, very unlikely to make a difference.

**Comment by nickmshelley** [comment]
I guess any observers could have cancelled it: https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/Operation.swift#L538.

Not sure if it would be worth adding another check after the observers are fired.

Thanks for the quick response @danthorpe!

**Comment by danthorpe** [comment]
Exactly - a Pull Request for this would be great! [😉](https://github.com/danthorpe/Operations/issues/new)

**Comment by pronebird** [comment]
From Apple documentation on `-start`:

```
The default implementation of this method updates the execution state of the operation and calls the receiver’s main method. This method also performs several checks to ensure that the operation can actually run. For example, if the receiver was cancelled or is already finished, this method simply returns without calling main.
```

**Comment by danthorpe** [comment]
This has been addressed here: https://github.com/danthorpe/Operations/pull/319/commits/b771716e53b71a233c8132795d58e4252d9a3e72

So, it is now safe to not bother `guard !cancelled else { return }` at the start of `execute`. However, I strongly advice still performing this check periodically while performing *work* in an `Operation` subclass.

**Comment by danthorpe** [comment]
Will close this now, feel free to comment if you have more questions!

**Comment by nickmshelley** [comment]
Thanks!

Should the docs be updated to not recommend checking cancelled at the beginning?
