### ISSUE TITLE
Properly handling CKErrorPartialFailure in CloudKit modification operations

### ISSUE THREAD

**Issue by swiftlyfalling** [danthorpe/Operations#290]
With the way things are currently structured in CloudKitOperation, handling CKErrorPartialFailure seems to be problematic.

In the event of an atomic CKModifyRecordsOperation that fails with CKErrorPartialFailure, the error's `userInfo[CKPartialErrorsByItemIDKey]` dictionary should contain an entry for every input savedRecord, and deletedRecordID (since any record saves/deletions that would have succeeded otherwise will fail with CKErrorBatchRequestFailed). Thus, one should be able to handle this case by using the current `setErrorHandlerForCode(.PartialFailure)`.

However, in the event that atomic = false (or if the zone lacks the CKRecordZoneCapabilityAtomic capability), the ModifyRecordsOperation will commit all record changes individually, and the `error.userInfo[CKPartialErrorsByItemIDKey]` dictionary will only contain entries for the savedRecord, deletedRecordIDs that were *not* saved or deleted. Other entries may have succeeded. Critical information (the savedRecords, deletedRecordIDs) from the original modifyRecordsCompletionBlock does not get passed through if attempting to handle this via `setErrorHandlerForCode`.

And the block passed to `setModifyRecordsCompletionBlock` won't be called, since there was an error.

**Comment by danthorpe** [comment]
Arrrh! That complicates things somewhat... I have not played around with atomic properties.

So, it would make sense to pass the "successful" results into the error handler?

**Comment by swiftlyfalling** [comment]
Yes. IMHO, the error handler should receive all the parameters from:
the `modifyRecordsCompletionBlock` for CKModifyRecordsOperation
the `modifyRecordZonesCompletionBlock` for CKModifyRecordZonesOperation
the `modifySubscriptionsCompletionBlock` for CKModifySubscriptionsOperation
the `markNotificationsReadCompletionBlock` for CKMarkNotificationsReadOperation

(All of those are documented as potentially failing with CKErrorPartialFailure.)

**Comment by danthorpe** [comment]
Okay, so I think, in that case, the way forward is to make the arguments the error recovery handler receives an associated type - and then it can be configured for each kind of `CKOperation`.

**Comment by swiftlyfalling** [comment]
Looked at this a bit more - that should be perfect.

**Comment by swiftlyfalling** [comment]
@danthorpe, Looked at this a bit more - that should be perfect.

**Comment by swiftlyfalling** [comment]
I would like to put my vote in for prioritizing this issue over:
`Support CloudKit error CKLimitExceeded by default in CloudKitOperation` #294

As #294 can currently be handled by framework consumers without framework modification, but this cannot.

**Comment by swiftlyfalling** [comment]
This issue also affects:

the `fetchRecordsCompletionBlock` for CKFetchRecordsOperation
the `fetchRecordZonesCompletionBlock` for CKFetchRecordZonesOperation
the `fetchSubscriptionCompletionBlock ` for CKFetchSubscriptionsOperation

(All are documented as potentially failing with CKErrorPartialFailure.)

**Comment by danthorpe** [comment]
@swiftlyfalling the requirements for this are satisfied now, in `development`, as each `CKOperationType` supports its own concrete error type which collects all returned data in the event of an error.
