### ISSUE TITLE
Operation inside a nested GroupOperation is initialised but not executed

### ISSUE THREAD

**Issue by plm75** [danthorpe/Operations#292]
With the following setup:

    class ViewController: UIViewController {
      
      var queue = OperationQueue()

      override func viewDidLoad() {
        super.viewDidLoad()
        
        let opBootstrap = OpBootstrap()
        queue.addOperation(opBootstrap)
      }
    }

    class OpBootstrap: GroupOperation {
      
      init() {
        print("opBootstrapdata - Initialize")
        let opFetchBootstrapData   = OpFetchData(urlString: "http://localhost:5000/v2/bootstrap")
        let opProcessBootstrapData = OpProcessBootstrapData()
        
        opProcessBootstrapData.injectResultFromDependency(opFetchBootstrapData)
        super.init(operations: [opFetchBootstrapData, opProcessBootstrapData])
      }
    }

    class OpFetchData: Operation, ResultOperationType {
      var result: String?
      
      init(urlString: String) {
        super.init()
      }
      override func execute() {
        print("opFetchData executed")
        result = "some result string"
        finish()
      }
    }
    class OpProcessBootstrapData: GroupOperation, AutomaticInjectionOperationType {
      var requirement: String?
      
      override func execute() {
        print("opProcessBootstrapData - Execute")
        let nestedGroupOp = NestedGroupOp(data: requirement)
        addOperation(nestedGroupOp)
        finish()
      }
    }

    class NestedGroupOp: GroupOperation {
      init(data: String?) {
        print("nestedGroupOp - Initialize")
        let someOp = SomeOp(data: data)
        super.init(operations: [someOp])
      }
    }

    class SomeOp: Operation {
      var data: String?
      
      init(data: String?) {
        print("someOp - Initialise with \(data)")
        self.data = data
        super.init()
      }
      override func execute() {
        print("someOp was executed with data: \(data)")
        finish()
      }
    }

I get the following output:

    opBootstrapdata - Initialize
    opFetchData executed
    opProcessBootstrapData - Execute
    nestedGroupOp - Initialize
    someOp - Initialize with Optional("some result string")

Not sure why someOp is initialised but never executed ?

**Comment by danthorpe** [comment]
Hi @plm75 - if you turn on verbose logging you'll get a lot more info about state changes:

```swift
import Operations
LogManager.severity = .Verbose
```

That'll make it a lot easier to see what is happening I think - I lost track somewhere in the SomeOp stuff.

**Comment by danthorpe** [comment]
Also - in `GroupOperation` - this is actually a bit of an issue (a documentation one) - but you need to call `super.execute()` at the end of your implementation.

**Comment by plm75** [comment]
@danthorpe 

Calling `super.execute()` solves the issue.  Thanks!
