### ISSUE TITLE
Implement an Operation that can open a URL in a SFSafariViewController or the Safari app itself

### ISSUE THREAD

**Issue by blg-andreasbraun** [danthorpe/Operations#314]
I wrote an Operation for an App that exhibits the following behavior:

- If the current iOS version supports SFSafariViewController, it opens the provided URL in an SFSafariViewController using WebpageOperation.
- If the app is the secondary app in a SplitView, it opens the provided URL in Safari as the primary app.
- If the current iOS version does not support SFSafariViewController, it opens the URL the old school way.

My problem right now is that WebpageOperation is iOS 9 or later, so I have to implement a fallback all the time in my app instead of doing it once.

I'd like to ask for some opinion on that matter.
Like if that should be a new Operation or an improved version of WebpageOperation.

**Comment by danthorpe** [comment]
Totally agree with you @blg-andreasbraun. When I added `WebpageOperation` initially it was a bit of an after thought, and I don't use it myself.

Pull requests are very welcome however, so if you want to refactor it to support the suggested behaviour (ideally with unit tests 😬) that would be great! 👌👍🙌

**Comment by blg-andreasbraun** [comment]
@danthorpe  I'll post a pull request once I have a nice solution and some tests :)
