### ISSUE TITLE
RetryOperation should provide a method to change the configure block for the next operation

### ISSUE THREAD

**Issue by swiftlyfalling** [danthorpe/Operations#332]
RetryOperation's `RetryFailureInfo` contains the block used to configure the next instance.

However, RetryOperation's `retry` handler currently has no way to pass back a different configuration block.

And any attempts by the `retry` handler to configure the next operation will be potentially overridden when `RepeatedOperation.addNextOperation()` executes its `configure` block *after* obtaining the next operation.

**Suggestion:** 
Provide the ability to change the configure block for the next operation.

Reference: https://github.com/danthorpe/Operations/pull/294#issuecomment-223760586

**Comment by danthorpe** [comment]
Implemented in #348.
