### ISSUE TITLE
Can't compile - errors.

### ISSUE THREAD

**Issue by razalur** [danthorpe/Operations#333]
Can't understand why so. I've installed this pod. But when I compile my project I have 49 errors in pod's files. What's wrong?

![oper_error](https://cloud.githubusercontent.com/assets/5269290/15816969/44344af0-2bde-11e6-93f6-628e67423905.png)

**Comment by blg-andreasbraun** [comment]
@razalur do you have the newest version of Xcode installed?

The #selector syntax is new, seems like you opened the project with an Xcode version lower than 7.3.

**Comment by razalur** [comment]
@blg-andreasbraun Yes! You are right! Thanks!
