### ISSUE TITLE
The best way for adding operations dynamically

### ISSUE THREAD

**Issue by razalur** [danthorpe/Operations#337]
Hello!

I have a list of guids. For every guid from this list I download some json data. But this list can have various number of items. So now I have BlockOperation with operations created in the loop. Does this way is right? May be there is more better approach for this task? And does this way guarantee that downlodAllJsonOperation will not finish before all operations inside BlockOperation?
```
class downloadAllJsonOperation: GroupOperation, AutomaticInjectionOperationType {
    var requirement: [String]?
    init() {
        super.init(operations: [])
   
        let operation = BlockOperation {
            for guid in self.requirement! {                        
                let taskOperation = URLSessionTaskOperation(...)
                                
                let parseAuthor = ParseAuthorOperation()
                parseAuthor.injectResultFromDependency(taskOperation)
                
                self.addOperation(parseAuthor)
                self.addOperation(taskOperation)
            }
        }
        addOperation(operation)
    }
}
```

**Comment by danthorpe** [comment]
Hi @razalur - interesting situation!

I think you're on the correct track, although I would not bother with the `BlockOperation`. And I'd maybe consider a `DownloadOperation` too. For example, you could define the "result" of this to be the `Author`, so that you're group could then have a result type of `[Author]`.

Something like this:

```swift

class DownloadOperation: GroupOperation {
    init(guid: String) {
        let taskOperation = URLSessionTaskOperation(...)
        let parseAuthor = ParseAuthorOperation()
        parseAuthor.injectResultFromDependency(taskOperation)
        super.init(operations: [parseAuthor, taskOperation])               
    }
}

class DownloadAllOperation: GroupOperation, AutomaticInjectionOperationType {
    var requirement: [String]?

    override func execute() {
        guard let guids = requirement where guids.count > 0 else {
            log.info("Did not receive any GUIDs")
            cancel()
            return
        }

        addOperations(guids.map(DownloadOperation.init))
        super.execute()
    }
}
```

**Comment by razalur** [comment]
Hm, thanks! I'm surprised by using execute() function and super.execute() in GroupOperation. I didn't saw it earlier in apple examples.
