### ISSUE TITLE
Whole Module Optimization

### ISSUE THREAD

**Issue by blg-andreasbraun** [danthorpe/Operations#349]
I wander why this isn't on for release. Is there any issue with that?

**Comment by danthorpe** [comment]
It's an oversight you can rest assured.

I'm about to run all the tests with the thread sanitiser on using Swift 2.3 & Xcode 8, and I'm sure I'll find some bugs. So I'll fix this up with those at the same time.

**Comment by danthorpe** [comment]
Oh, thread sanitizer requires Swift 3.0. I was hoping that any issues it uncovered I could commit back into `development` with Swift 2.2.

Okay, will fix this directly.
