### ISSUE TITLE
Contacts Example for ios9 

### ISSUE THREAD

**Issue by srikanthpandeti** [danthorpe/Operations#368]
Access contacts in ios9 is different. Please help in fetching contacts with example

**Comment by danthorpe** [comment]
Hello, @srikanthpandeti what have you got so far? If you are asking for help with `Contacts.framework` I suggest you look at the documentation for it online, and the sessions from WWDC 2015 where it was introduced.

If you are looking for assistance with using Contacts in _Operations_, I cannot write your code for you, so please show me what you have already.

**Comment by srikanthpandeti** [comment]
I need your assistance for authorizing Contacts using Operations

**Comment by danthorpe** [comment]
Hi, @srikanthpandeti - this fails with `ContactsPermissionError`.

**Comment by srikanthpandeti** [comment]
Thanks, @danthorpe

**Comment by srikanthpandeti** [comment]
i'm get error when i'm passing givenName -> **CNContactGivenNameKey** keysToFetch   

    let cn = GetContacts(predicate: .InContainerWithID(.Default), keysToFetch: [CNContactGivenNameKey])
