### ISSUE TITLE
How to do App Startup Server Login?

### ISSUE THREAD

**Issue by danthorpe** [danthorpe/Operations#369]
This is a question from Erik asked on the Slack channel:

> Hello!
> I’m trying to wrap my head around the implementation of Operations. Up until now I have used my own implementation using GCD to get the result I want, but the code is messy and I want to get started with Operations. (I am a hobby developer, sorry if my questions are stupid.) Here is the operation flow I want:
> 
> Order of operations:
> 
> //1. Server Check Operation
> - Initiated on app launch
> - Sends a query to my server and returns some flags (accessGranted, databaseUpdateRequired)
> 
> //1A. Database Update Operation
> - Initiated if 'databaseUpdateRequired' returns true from Operation 1
> 
> //2. Login Operation
> - User decides when to log in to a service
> - If 'Server Check Operation' returns 'accessGranted' = false, the operation should not start
> - When user is logged in, data is retrieved
> 
> //3. Parse Operation
> - Data from the login operation is parsed
> 
> Operation 2 will be initiated by the user (tapping button), but it should not start until Operation 1 is complete.
> 
> Operation 3 depends on Operation 2 and Operation 1A to be complete. (Operation 1A may not exist if no datebase update is required).
> 
> ***
> - What is the best way to accomplish this?
> - If I add the 'Server Check Operation' in the AppDelegate, how can I add it as a depedency to 'Login Operation' at a later stage?
> - Scenario: 'Server Check Operation' is complete, but the 'Database Update Operation' is running. How can this be signalled to 'Parse Operation'?
> - Scenario: Op 3 depends on Op 1A, but only if Op 1A is actually running. How can this be accomplished?

**Comment by fishfisher** [comment]
Excellent answer, @danthorpe. Thank you.
In your answer, all of the operations are grouped into a GroupOperation. In some cases the user will never initiate the Login (and in relation the parsing). This will only happen if the user does that specific action. Is this achievable?

**Comment by danthorpe** [comment]
@fishfisher - absolutely, really good question.

In the example above I've used a `ServerRequest` operation to do the login. But, perhaps this needs to change, so that you actually wrap your UI presentation of the login screen with the button enabled, as an Operation. How would this work?

Well, it would be similar to `AlertOperation` essentially you present some UI in the `execute` stage of the operation, and when the UI is dismissed the operation is _finished_ either by calling `cancel()` or `finish()`. So, if the use dismisses the UI without tapping the login button - just call `cancel()`. However, if the user taps the button - then it finishes. This is a single operation, it just presents/dismisses/taps button.

You can then include this inside another `GroupOperation` which essentially will

1. Present the UI
2. Perform login (dependent on UI finishing without error)
3. Perform parse (dependent on Login finishing without error)

And the whole group has the same login server condition as in the example above. The result of the Login group would then be your `User` type.
