### ISSUE TITLE
Can I add a condition for result dependency operation 

### ISSUE THREAD

**Issue by srikanthraju** [danthorpe/Operations#370]
class SyncData: GroupOperation {
      
         init() {

              let fetch = FetchDataOperation()
              let store = StoreDataOperation()

              store.injectResultFromDependency(fetch)
              let gop = GatedOperation(store) { () -> Bool in

                     return true
              }

              super.init(operations : [fetchCities, gop])
         }
    }

In the above code, 
**fetch** is fetching data from the remote
**store** is to save the fetched data in certain conditions only

so, I need to add a condition for store operation and the result is from the fetch operation.

**Comment by danthorpe** [comment]
Well, the `.injectResultFromDependency()` does this for you. It sets up the dependency relationship and observers which will inject the result into the receiver as its requirement.

You will also want to add a condition to ensure that all dependencies must succeed to perform the store:

```swift
store.addCondition(NoFailedDependenciesCondition())
```

**Comment by srikanthpandeti** [comment]
I want to check the success result data manually and decide whether to store data or not.

**Comment by danthorpe** [comment]
Okay then, you can use a block

```swift
store.injectResultFromDependency(fetch) { op, dep, errors in 
    // Here we have access to both operations, plus any errors
    // from the dependency.
}
```

See [Injecting Results](https://operations.readme.io/docs/injecting-results) in the programming guide.
