### ISSUE TITLE
Mutually Exclusive wiki entry

### ISSUE THREAD

**Issue by ryanjm** [danthorpe/Operations#384]
Right now the [Mutually Exclusive](https://github.com/danthorpe/Operations/wiki/Mutually-Exclusive) wiki page is blank.

This is what I propose as the first version. This is based on the existing section in the [readme.io site](https://operations.readme.io/docs/conditions) and based on my conversation with @danthorpe.

# Mutually Exclusive

A condition can assert whether its operation should be evaluated with mutual exclusion of other operations. This can be very handy for stopping operations from executing at the same time.

For example, if our application presents a modal alert, by executing this in the context of an operation with a mutually exclusive condition, we will prevent any other modal alert from being presented. Given the nature of event based applications this would otherwise be quite tricky. With Operations this can be done like this:

```
let alert = AlertOperation(presentAlertFrom: viewController)
alert.title = NSLocalizedString("Hello World", comment: "Hello World")
queue.addOperation(alert)
```

AlertOperation adds a mutually exclusive condition to itself during its initializer.

If your operation runs in isolation, it might be more beneficial to add it to its own queue which has a `maxConcurrentOperationCount` set to `1`. If your operation runs  as a part of a group of operations (using either `GroupOperation` or simply queuing up multiple operations at the same time), then using mutual exclusion makes more sense.

> Note: mutual exclusion does not stop subsequent operations from running. The operation will run once the mutually exclusive blocking operation in front of it finishes.

## Implementation

To add mutual exclusion to your own operation you’ll need to create an `enum` which will be used to define the mutual exclusion. Name it based on the type of operation you’ll be performing.

```
public enum CoreDataWork { }
```

Then in your operation, add a condition for mutual exclusion:

```
self.addCondition(MutuallyExclusive<CoreDataWork>)
```

If you are going to use this mutual exclusion in multiple operations it might be useful to create a typealias for this mutual exclusion:

```
public typealias CoreDataExclusive = MutuallyExclusive<CoreDataWork>
```

Then you can add it to your operation with:

```
self.addCondition(CoreDataExclusive())
```

## Warning

You can cause a deadlock in your program if you add the same exclusion on a group operation and one of it's children.

**Comment by danthorpe** [comment]
Done - https://github.com/danthorpe/Operations/wiki/Mutual-Exclusion

Thanks @ryanjm!
