### ISSUE TITLE
AlertOperation doesn't fire in 3.0.0

### ISSUE THREAD

**Issue by ryanjm** [danthorpe/Operations#387]
Were there any major changes to the way AlertOperation works in 3.0.0? Code which was working before doesn't anymore and my queue ends up with two operations which never complete:

```
(lldb) po [[mainOperationQueue] operations]
<__NSArrayM 0x7f96623bbf90>(
<_TtGC10Operations14AlertOperationCSo16UIViewController_: 0x7f96611a3ce0>{name = 'Error'},
<_TtGC10Operations11UIOperationCSo17UIAlertControllerCSo16UIViewController_: 0x7f965ee640c0>{name = 'UIOperation<UIAlertController>'}
)
```

From what I can tell, `execute` is never called on `UIOperation`. But I don't see any changes between 2.10 and 3.0.0 with that class. I've tried adding break statements into the Operation code base but it doesn't let me access the variables there:

```
(lldb) po self
error: <EXPR>:10:9: warning: initialization of variable '$__lldb_error_result' was never used; consider replacing with assignment to '_' or removing it
    var $__lldb_error_result = __lldb_tmp_error
    ~~~~^~~~~~~~~~~~~~~~~~~~
    _
<EXPR>:16:5: error: use of unresolved identifier '$__lldb_injected_self'
    $__lldb_injected_self.$__lldb_wrapped_expr_43(  
```

I'm creating my alert in a pretty standard way:

```swift
let alert = AlertOperation(presentAlertFrom: presentationContext)
alert.title = "Error"
alert.message = msg
queue.addOperation(alert)
```

What can I do to check why those operations aren't being run?

**Comment by danthorpe** [comment]
Hmm - what does the verbose log say?

```
alert.log.severity = .Verbose
```

**Comment by ryanjm** [comment]
```
Error: >>> MutuallyExclusive<UIViewController>
Error: >>> MutuallyExclusive<Alert>
Error: Initialized -> Pending
Error: Pending -> Executing
Error: Will Execute
Error: Did produce UIOperation<UIAlertController>
UIOperation<UIAlertController>: Initialized -> Pending
```

**Comment by danthorpe** [comment]
@ryanjm - just looking into this. On the [examples project](https://github.com/danthorpe/Examples/blob/development/Operations/Permissions/Permissions/MainController.swift#L83) this is all working fine.

The issue in your code is almost certainly one of the following:

1. An operation is not getting "finished"
2. There is a subtle issue with mutual exclusivity resulting in a deadlock.

Try turning verbose logging on for all operations, put this in your application delegate startup callback:
```swift
LogManager.severity = .Verbose
```

then trace through the `>>> MutuallyExclusive` messages. They should all have matching `<<< MutuallyExclusive` log entries.

**Comment by ryanjm** [comment]
I've added the verbose logging and here is everything from the Alert (which I named "Alert from Error Observer"):

```
Alert from Error Observer: >>> MutuallyExclusive<UIViewController>
Alert from Error Observer: >>> MutuallyExclusive<Alert>
Condition Evaluator for: Alert from Error Observer: Initialized -> Pending
Alert from Error Observer: Initialized -> Pending
Condition Evaluator for: Alert from Error Observer: Pending -> Executing
Condition Evaluator for: Alert from Error Observer: Will Execute
MutuallyExclusive<UIViewController>: Initialized -> Pending
MutuallyExclusive<Alert>: Initialized -> Pending
MutuallyExclusive<Alert>: Pending -> Executing
MutuallyExclusive<UIViewController>: Pending -> Executing
MutuallyExclusive<Alert>: Will Execute
MutuallyExclusive<UIViewController>: Will Execute
MutuallyExclusive<Alert>: Executing -> Finishing
MutuallyExclusive<UIViewController>: Executing -> Finishing
MutuallyExclusive<Alert>: Will finish with no errors.
MutuallyExclusive<UIViewController>: Will finish with no errors.
MutuallyExclusive<Alert>: Finishing -> Finished
MutuallyExclusive<UIViewController>: Finishing -> Finished
MutuallyExclusive<Alert>: Did finish with errors: []
MutuallyExclusive<UIViewController>: Did finish with errors: []
Condition Evaluator for: Alert from Error Observer: Executing -> Finishing
Condition Evaluator for: Alert from Error Observer: Will finish with no errors.
Condition Evaluator for: Alert from Error Observer: Finishing -> Finished
Condition Evaluator for: Alert from Error Observer: Did finish with errors: []
Alert from Error Observer: Pending -> Executing
Alert from Error Observer: Will Execute
Alert from Error Observer: Did produce UIOperation<UIAlertController>
UIOperation<UIAlertController>: Initialized -> Pending
```

Everything else in the log lined up properly and went through the entire flow. None of them had `MutuallyExclusive<UIViewController>` or `MutuallyExclusive<Alert>`. If you want the full log, ping me on Slack and I'll give you a gist with it all.

From what I can tell it looks like both MutuallyExclusive conditions complete just fine and therefore the alert continues to run. I don't know why the `UIOperation` doesn't continue.

**Comment by ryanjm** [comment]
I've downloaded and run the example project you reference. The only difference I see in my code is where my operation is being generated. 

I'm creating mine from an observer and then adding it to my global queue. This also means that I'm having to "find" the `UIViewController` to present the alert from, but when I put a break point into my code, the view controller is the one I'm expecting to see.

I've even tested the presentation method directly in that view controller and it works as expected (no surprise there):

```
UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Test message" message:@"msg" preferredStyle:UIAlertActionStyleDefault];
[alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
    NSLog(@"Done");
}]];
[self presentViewController:alert animated:true completion:nil];
```

I've even tried changing which queue the alert operation is put on, but that didn't change anything:

```
OperationQueue.mainQueue().addOperation(alert)
```

Those two operations just remain stuck on that queue instead.

Very strange.

**Comment by ryanjm** [comment]
I've put a bunch of break statements throughout operations and I see the `UIOperation` get added to the queue via the `ProducedOperationObserver`. But the `main` is never called on the `UIOperation`. The queue still exists, nothing should be blocking it, but it is just never run.

I think I'm going to have to manually work around this for now (not sure how I'll do that). I have no idea where to take it from here. Any ideas?

**Comment by ryanjm** [comment]
Ended up being one of those one-liner mistakes. 

This is my fault (of course). I had recently added a `maxConcurrentOperationCount` of `1` on my queue, so those two queues we blocking each other. The `Alert` was waiting for the `UIOperation` to finished, but it couldn't get started because the queue was already running something (the `alert`).

**Comment by danthorpe** [comment]
So, ended up kinda being a deadlock?

This is one of those situation where it would make sense to have a timeout observer added to every `Operation` instance by default in `#if debug #endif` to warn if an operation has been running for longer than 3 seconds or something.

**Comment by ryanjm** [comment]
Yes, it was a deadlock, just not a mutual exclusion issue.

The timeout observer would be an interesting solution, but I wonder if that would just dirty the code. I'm not sure how necessary it would be. The most the error message could say is "Timed out, \(operation) couldn't finish in a reasonable time." And then it'd be up the the developer to figure out why. Additionally, there might be a case where you _want_ an operation running longer (I have no idea what that case would be, but it might be out there).

But, this is just a good lesson to know regarding limiting the number of operations that run. Alert creates a ui operation and waits for that operation to finished before it finishes. Therefore if they are on the same queue, you can't limit that queue.
