### ISSUE TITLE
dependent operations are started even when it parent operation fails

### ISSUE THREAD

**Issue by hassanrazakhalid** [danthorpe/Operations#388]
Hello
i am using this framework and its really great. I just want to have clarification should dependent operations be allowed to run if operations on which they depend fails like A depends on B. If A ends finsihWithError then should B be allowed to execute. If its is not allowed then it a bug i guess. :) many thanks for this great framework.

**Comment by morisk** [comment]
Hi, 
If the're dependancy failed or canceled they still run. 

When you want to prevent them from running you should add condition: 'notfaileddepenancies'.

**Comment by hassanrazakhalid** [comment]
got it thx

**Comment by danthorpe** [comment]
Yep, thanks @morisk for answering. This is explained in a bit more detail in the [wiki](https://github.com/danthorpe/Operations/wiki/Preventing-a-group%27s-child-operations-from-running%2C-if-one-fails).
