### ISSUE TITLE
Alternate paths through a dependency chain

### ISSUE THREAD

**Issue by jshier** [danthorpe/Operations#52]
So I have a chain on three operations. However, if the first operation fails, I would like to skip to the third operation. How can I express this? My current idea is to build the full dependency chain and then in `operationDidFinish` check to see which operation finished. If it's the first, check the property I care about, and if it's good, let the process continue unchanged. If it's bad, cancel the current operations in the queue and then readd the third operation. Is there any way to express this behavior in cleaner fashion?

**Comment by danthorpe** [comment]
Well, you can attach a `BlockCondition` to the 2nd operation.

The condition will only allow an operation to execute if the block it is initialized evaluates truthfully. So you would need to test some property of your group operation inside that block. i.e. something like this...

```swift
class ThreeOperations: GroupOperation {
   let first = OperationWithProperty()
   let second: Operation()
   let third: Operation()
   init() {
      second = Operation()
      second.addDependency(first)
      third = Operation()
      third.addDependency(second)
      super.init(operations: [first, second, third])
      second.addCondition(BlockCondition { [unowned self] in
            return self.first.propertyIsSet
      })
   }
}
```

**Comment by jshier** [comment]
I didn't realize `OperationCondition`s didn't kill the entire dependency chain. Is that configurable? If I want to kill the entire chain, how could I do that?

**Comment by danthorpe** [comment]
What do you mean by "kill the entire dependency chain"?

**Comment by danthorpe** [comment]
The dependency management of `Operation` is the same as `NSOperation`. That means that eventually all operations Finish. And when they finish, then any `NSOperation`s which are depending on them become Ready.

The concept of a "Success" and "Failure" is something which you are attributing to whatever the task is your `NSOperation` subclass is performing. Neither `NSOperation` nor `Operation` knows anything about this.

When you attach a condition to an `Operation` where the condition evaluates to a failure, then that operation will still finish - but it will do so without executing.

This means that any operations which were depending on it will then become ready.

If this is unexpected behavior, you might find it useful to look over the docs of `NSOperation` again.

However, what you can do is attach a `NoCancelledCondition` to an operation, which is a condition which requires that all it's dependencies succeeded.

**Comment by jshier** [comment]
Thanks for the explanation and solution.

**Comment by danthorpe** [comment]
@jshier did `NoCancelledCondition` and `BlockCondition` work for you?

**Comment by jshier** [comment]
I'll have to create some tests to make sure, but the logic sounds correct. I should be able to write some tests soon to double check.
