### ISSUE TITLE
Condition to cancel/skip an operation without error?

### ISSUE THREAD

**Issue by sixten** [danthorpe/Operations#77]
Say that I have an operation that I want to perform when certain conditions are met, but not otherwise, and that skipping the operation should be done without prejudice. This becomes especially important within a `GroupOperation`, where any failed operation causes the group to fail.

My first impulse would be to have the condition yield `Satisfied`, but cancel the operation. But `OperationConditionEvaluator` specifically fails any operations that are cancelled when it processes the condition results, even if they are all satisfied.

I suppose I could have the operation cancel itself (or, really, finish immediately) if the conditions aren't met when it tries to start, but this checking might apply to a number of different operations, and I'd like to keep that logic in a composable chunk.

How would you recommend approaching this problem within this framework?

**Comment by danthorpe** [comment]
Hi, you could use the `BlockCondition`,

```swift
op.addCondition(BlockCondition { return self.shouldOperationBeExecuted() })
```
Essentially, just provide a block which returns a `Bool`, and the block is executed when the conditions are evaluated. Returning `false` will mean the condition fails with error `BlockCondition.Error.BlockConditionFailed`

**Comment by sixten** [comment]
> Returning `false` will mean the condition fails with error `BlockCondition.Error.BlockConditionFailed`

Hmm. Doesn't that exhibit the same behavior I'm trying to avoid, then? Namely: condition fails -> operation fails -> containing operation fails?

**Comment by danthorpe** [comment]
Hmm, well, `NSOperation`s don't really have a concept of failure, they finish, and they may be cancelled. `Operation` collects aggregate errors, but the underlying `NSOperation` still finishes. And an `Operation` which finishes with an error doesn't stop and operations which depend on it from starting. (I've discovered that this is a common misconception).

So, is it a problem if your `GroupOperation` finishes with an error from one of it's children?

**Comment by danthorpe** [comment]
I've corrected my answer which misleadingly uses the term "failed".

**Comment by danthorpe** [comment]
So, to clarify your summation:

> Namely: condition fails -> operation fails -> containing group operation fails?

It's really... condition fails -> operation finishes without executing, with error from condition, -> containing group finishes, including error from condition.

**Comment by sixten** [comment]
I realize that `NSOperation` doesn't have a concept of failure, but `Operation` (and `GroupOperation`) explicitly do. And "one of this operation's conditions wasn't satisfied" is given equal weight and visibility to "something this operation was doing went horribly awry." From the perspective of calling code, these failures are equivalent until and unless I do a bunch of casting and filtering to verify that, yes, the error is a failed condition of the type that means that everything is OK, or, no, this is a real failure. That's compounded in the case of a `GroupOperation`, which aggregates all errors from all children into one big list (without any tie back to the source).

So what I'd like is to find a way to define a condition that prevents the sub-operation from executing, but which does not create a false-negative failure that I have to later filter back out in my error-handling code.

**Comment by danthorpe** [comment]
Well, did you try just using a `GatedOperation`, which can be used in exactly the same way as a block condition.

```swift
queue.addOperation(GatedOperation(operation: myOperation, gate: shouldOperationBeExecuted))
```

And if you look at how `GatedOperation` works, you'll see that it's just a group operation which executes a block and adds the composed operation to it's queue if the result is true.

**Comment by sixten** [comment]
Ah! I hadn't noticed that class, no. I guess that answers the question of how you'd accomplish that. (I'd contemplated something similar: an operation that would act as a proxy, always finishing successfully, but conditionally producing the "real" operation if the preconditions were met.)

It still seems a little roundabout to me, but I don't really see a way to make conditions accomplish this with any elegance.

**Comment by danthorpe** [comment]
Well, this is a class (along with ComposedOperation) which isn't in the Apple sample code. 

I think probably because it's relatively trivial to determine whether or not to add an operation to a queue or not.

And, I'd go so far as to say, think twice before using GatedOperation as a child in a group - as it's going to needlessly use another internal operation queue. In this scenario I would just execute the logic as part of the group, override execute(), if the "conditions" are right, add the operation. Call super.execute().

If you don't have any other child operations, then you can avoid having to subclass GroupOperation and use GatedOperation directly.
