### ISSUE TITLE
swift_2.0 branch broken?

### ISSUE THREAD

**Issue by jshier** [danthorpe/Operations#80]
I know it was just updated, but I'm getting a bunch of build errors when I try to build the framework through CocoaPods. I get a bunch of 'PresentingViewController is ambiguous for type lookup in this context' errors, due to the duplicated protocol definition in `UIOperation.swift` and `UIOperations.swift`. Once that's fixed, I still get bunch of errors about the duplicate `UIOperation` declarations. Perhaps something didn't merge correctly?

**Comment by danthorpe** [comment]
Arrrrrr!!! Damnit! Okay, sorry, I must have fucked up a merge.

**Comment by danthorpe** [comment]
@jshier try now?

**Comment by jshier** [comment]
@danthorpe Works now, thanks for the quick turnaround.

**Comment by danthorpe** [comment]
n.p. I should add figure out a way to test this in CI.
